# Generated by Django 3.0.5 on 2021-01-28 22:58

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('right_side', models.TextField()),
                ('left_side', models.TextField()),
                ('result', models.TextField()),
            ],
        ),
    ]
