# Generated by Django 3.0.5 on 2021-01-31 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_trade_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='image',
        ),
    ]
